version: '3'


vars:
  VERSION:
    sh: scripts/dev_version.sh
  LD_FLAGS: '-ldflags="-X pkg/version.Version={{.VERSION}}"'
  REPO_FOLDER: github.com/PiotrKowalski/image-manager
  APP_FOLDER: internal/app
  DAPR_CONFIG: dapr/config.yaml
  DAPR_COMPONENTS: dapr/components

tasks:
  build-linux:
    env:
      GOOS: "linux"
      GOARCH: "amd64"
    cmds:
      - go build {{.LD_FLAGS}}  {{.REPO_FOLDER}}/{{.APP_FOLDER}}/{{.CLI_ARGS}}

  proto:
    summary: |
      Generate api files from proto specification
    cmds:
      - cd pkg/api/imagemanagerapis && buf mod update && buf build
      - cd pkg/api && buf generate imagemanagerapis

  run:
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      APP_PORT:
        sh: scripts/free_app_port.sh
      HTTP_PORT:
        sh: scripts/free_http_port.sh
    dotenv: ['./{{.APP_FOLDER}}/{{.CLI_ARGS}}/.env', '.env' ]
    cmds:
      - dapr run
        --app-id {{.CLI_ARGS}}
        --app-port {{.APP_PORT}}
        --app-protocol grpc
        --components-path {{.DAPR_COMPONENTS}}
        --config {{.DAPR_CONFIG}}
        --log-level debug
        go run {{.REPO_FOLDER}}/{{.APP_FOLDER}}/{{.CLI_ARGS}}

