version: '3'


env:
  VERSION:
    sh: scripts/dev_version.sh
  LD_FLAGS: '-ldflags="-X pkg/version.Version={{.VERSION}}"'
  REPO_FOLDER: github.com/PiotrKowalski/image-manager
  APP_FOLDER: internal/app
  DAPR_CONFIG: dapr/config.yaml
  DAPR_COMPONENTS: dapr/components

tasks:
  build-linux:
    env:
      GOOS: "linux"
      GOARCH: "amd64"
    cmds:
      - go build {{.LD_FLAGS}}  {{.REPO_FOLDER}}/{{.APP_FOLDER}}/{{.CLI_ARGS}}

  proto:
    summary: |
      Generate api files from proto specification
    cmds:
      - cd pkg/api/imagemanagerapis && buf mod update && buf build
      - cd pkg/api && buf generate imagemanagerapis

  run:
    dir: .
    vars:
      APP_PORT:
        sh: scripts/free_app_port.sh
      GRPC_PORT:
        sh: scripts/free_grpc_port.sh
      HTTP_PORT:
        sh: scripts/free_http_port.sh
    dotenv: ['./{{.APP_FOLDER}}/{{.CLI_ARGS}}/.env', '.env' ]
    cmds:
      - dapr run
        --app-id {{.CLI_ARGS}}
        --app-port {{.APP_PORT}}
        --dapr-grpc-port {{.GRPC_PORT}}
        --dapr-http-port {{.HTTP_PORT}}
        --components-path {{.DAPR_COMPONENTS}}
        --config {{.DAPR_CONFIG}}
        --log-level debug
        go run ./{{.APP_FOLDER}}/{{.CLI_ARGS}}

# Not working for now
#  run-all:
#    dir: .
#    dotenv: [ '.env' ]
#    cmds:
#      - ./scripts/run_service.sh downloader
##      - ./scripts/run_service.sh resizer

